[project]
name = "xyra-rate-limiter-example"
version = "0.1.0"
description = "Rate limiter middleware example for xyra framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "xyra>=0.1.3",
]

[project.scripts]
rate-limiter-demo = "rate_limiter_example:main"