[project]
name = "xyra-websocket-example"
version = "0.1.0"
description = "WebSocket example for xyra framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "xyra>=0.1.3",
]

[project.scripts]
websocket-chat = "main:main"